#%RAML 1.0
title: Contact Us API
version: v1
description: Contact Us Module
baseUri: http://acc.com/{version}/contact
mediaType: application/json
/feedback:
  description: Submit the feedback
  post:
    body: 
      application/json:
        description: Provide the detail information
        example: |
          {
            "patientId": 3434,
            "subject": "This is sample title", 
            "message": "Sample Descritpion"
          }
    responses:
      200:
        body: 
          application/json:
            example: |
               {                  
                "status": true,
                "message": "feedback submitted"
               }
      403:
         body: 
          application/json:
            example: |
              {
               "status": false,
               "errorMessage": "Unable to save the data",
               "errorCode": "105"
              }
/callback:
  description: Submit the API call
  post:
    body: 
      application/json:
        description: Provide the detail information
        example: |
          {
           "patientId": 3434,
           "reason": "reason for callback/appointment",
           "requestType":"callback/appointment"
          }
    responses:
      200:
        body: 
          application/json:
            example: |
              {
                "status": true,
                "statusCode": 200,
                "message": "Your reques for callback/appointment has been submitted.",
              }
      403:
         body: 
          application/json:
            example: |
              {
                 "status": false,
                 "errorMessage": "Unable to save the data",
                 "errorCode": "105",
                 "statusCode": 403
              }