#%RAML 1.0
title: ACC
version: v1
description: Authentication Module
baseUri: http://localhost:8082/acc-api/{version}
#baseUri: https://mocksvc.mulesoft.com/mocks/b778e3b1-581c-4515-bb18-b4c740ae1fdd/auth
mediaType: application/json
/auth:
  /login:
    description: Make a request to login in the system
    post:
      body: 
        application/json:
          description: Provide the login information
          example: |
                {
                  "patientId": 32323,
                  "password": "Adsd#d"
                }
          
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status": true,
                  "patientId": "1", "name": "Ashish",
                  "userEmail": "abc@xyz.com",
                  "accessToken": "289dhd8h4kjnfjk89248h4f894398g989fafa7f9a7fa793g298",
                  "message": "login successfull",
                  "statusCode": "200"
                }
        401:
           body: 
            application/json:
              example: |
                {
                  "status": "false",
                  "errorMessage": "Login Failed",
                  "errorCode": "1001",
                  "statusCode": "401"
                }
  
  /SendOTP:
    description: Send the OTP to the target system
    post:
      body: 
        application/json:
          description: Provide the login information
          example: |
            {
              "patientId": "32323",
              "otpType": "1" 
            }
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status" : "true",
                  "message" : "Otp send to your registered mobile no",
                  "statusCode": "200" 
                }
        401:
           body: 
            application/json:
              example: |
                {
                   "status": "false",
                   "errorMessage": "OTP not matched",
                   "errorCode": "1001",
                   "statusCode": "401"
                }
           
  /OTPVerfication:
    description: Validate the OTP
    post:
      body: 
        application/json:
          description: Provide the login information
          example: |
            { 
              "patientId": "32323",
              "OTP": "434343",
              "otpType": "1"
            }
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status": "true",
                  "message" : "otp verified",
                  "statusCode": "200" 
                }
        401:
           body: 
            application/json:
              example: |
               {
                 "status": "false",
                 "errorMessage": "OTP not matched",
                 "errorCode": "1001",
                 "statusCode": "401" 
               }
          
  /resetPassword:
    description: Reset Password after correct OTP
    post:
      body: 
        application/json:
          description: Provide the login information
          example: |
            { 
              "patientId": "32323",
              "newPass": "A33#ds" 
            }
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status": "true",
                  "message" : "Password reset successful",
                  "statusCode": "200"
                }
        403:
           body: 
            application/json:
              example: |
                {
                  "status": "false",
                 "errorMessage": "Unable to reset the password",
                 "errorCode": "1002",
                 "statusCode": "403"
                }
  /chkAgreementStatus/patientId/{id}:
    description: Check Agreement Status
    get:
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                   "status": "true",
                   "agreementStatus": "Accepted",
                   "message" : "Terms & conditions already accepted",
                   "statusCode": "200"
                }
        401:
           body: 
            application/json:
              example: |
                {
                 "status": "false",
                 "errorMessage": "Not Accepted",
                 "errorCode": "1002",
                 "statusCode": "401"
                }
  /takeAgreement:
    description: Agreement Taking API
    post:
      body: 
        application/json:
          description: Provide the login information
          example: |
            { 
             "patientId": 1001,
             "isAgree": "Yes" 
            }
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status": "true",
                  "message": "save successfully",
                  "statusCode": "200"
                }
        403:
           body: 
            application/json:
              example: |
                {
                 "status": "false",
                 "errorMessage": "Unable to save the agreement",
                 "errorCode": "1002",
                 "statusCode": "403"
                }  
  /userDetail/patientId/{id}:
    description: User Detail API
    get:
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                "status": "true",
                "message": "User info fetched",
                "statusCode": "200",
                "data": {
                   "patientId": "1",
                   "name": "Ashish",
                   "userEmail": "abc@xyz.com",
                   "profilePic": "http:///www.test.com/test.jpg",
                   "ethnicOrigin": "",
                   "occupation": "",
                   "companyName": "",
                   "languages": "English, Urdu",
                   "DOB": "1984-10-23",
                   "height": "165 cms",
                   "weight": "65 kg",
                   "contactTime": "",
                   "maritalStatus": "",
                   "homeAddress": "",
                   "physicalChallenged": "Yes",
                   "challengesDetail": "",
                    "foodAllergy": "No",
                   "drugAllergy": "Yes",
                   "drugAllergyDetail": "",
                   "wakeupTime": "",
                   "breakfastTime": "",
                   "dinnerTime": "",
                   "bedTime": "",
                   "extraField1": "",
                   "extraField2": "",
                   "extraField3": "",
                  }
                }
        401:
           body: 
            application/json:
              example: |
                {
                 "status": "false",
                 "errorMessage": "Unable to get the details",
                 "errorCode": "1002",
                 "statusCode": "401"
                 }
  /changePassword:
    description: Change Password API
    post:
      body: 
        application/json:
          description: Provide the login information
          example: | 
            { 
             "patientId": "32323",
              "oldPass": "B33#ds",
              "newPass": "A33#ds"
            }
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                "status": "true",
                "message": "password changed successfully",
                "statusCode": "200" 
                }
        400:
           body: 
            application/json:
              example: |
                {
                  "status": "false",
                  "errorMessage": "Unable to change the password",
                  "errorCode": "105",
                  "statusCode": "400"
                 } 

