#%RAML 1.0
title: Notification and Plan API
version: v1
description: Notification Module
baseUri: http://acc.com/notification-api/{version}
mediaType: application/json
/getAllNotification:
    description: To get the all notification
    get:
      queryParameters: 
        startDateTime:
          description: "Give the device name"
          required: true
          type: datetime-only
          example: 2015-07-04T21:00:00
      responses:
        200:
          body: 
            application/json:
              example: |
                {
                  "status": true,
                  "message": "notification list",
                  "statusCode": 200
                  "data": [
                    {
                      "id" : 1 
                       "subject": "Notification 1",
                       "dateTime": <Date time in UTC>,
                       "shortDescription": "",
                       "imageURL": ""
                    },
                    {
                      "id" : 2 
                       "subject": "Notification 2",
                       "dateTime": <Date time in UTC>,
                       "shortDescription": "",
                       "imageURL": ""
                    },
                  ]
                }
        403:
           body: 
            application/json:
              example: |
               {
                  "status": false,
                   "errorMessage": "Unable to fetch the list",
                   "errorCode": "105",
                   "statusCode": 403
               }
/getNotificationDetail:
  get:
    queryParameters: 
      notificationId:
        description: "Give the notification ID"
        required: true
        minLength: 3
        type: string
        example: "23455"
    responses:
        200:
          body: 
            application/json:
              example: |
                {
                   "status": true,
                    "message": "notification list",
                    "statusCode": 200,
                    "data": 
                      {
                        "id" : 1 
                         "subject": "Notification 1",
                         "imageURL": "",
                         "message": "Notification 1 Message",
                         "datetime": <Date time in UTC>
                      }
                }
        403:
           body: 
            application/json:
              example: |
               {
                  "status": false,
                   "errorMessage": "Unable to get  the notification details",
                   "errorCode": "105",
                   "statusCode": 403
               } 
/getAllPlan:
  get:
    responses:
        200:
          body: 
            application/json:
              example: |
                {
                   "status": true,
                   "statusCode": 200,
                   "plans": [
                     {
                      "planId": 1,
                      "planName": "Test Plan",
                      "planDetails": "Test Plan"
                     },
                     {
                      "planId": 2,
                      "planName": "Plan 2",
                      "planDetails": "Test Plan"
                     }
                  ]
                }
        403:
           body: 
            application/json:
              example: |
               {
                  "status": false,
                   "errorMessage": "Unable to get the plan",
                   "errorCode": "105",
                   "statusCode": 403
               }
/getHomeBanners:
  description: To home banners details 
  get:
    queryParameters: 
      requestType:
        description: "Give the request type"
        required: true
        type: string
        example: "Promotional"
    responses:
      200:
        body: 
          application/json:
            example: |
              {
                "status": true,
                "statusCode": 200,
                "Banners": [
                 {
                  "bannerId": 1,
                  "imageURL": "http://www.google.com/1.jpg",
                  "linkURL": "http://www.google.com"
                 },
                 {
                  "bannerId": 2,
                  "imageURL": "http://www.google.com/2.jpg",
                  "linkURL": ""
                 }
                ]
              }
      403:
         body: 
          application/json:
            example: |
             {
                "status": false,
                 "errorMessage": "Unable to get the details",
                 "errorCode": "105",
                 "statusCode": 403
             }
