#%RAML 1.0
title: Patient API
version: v1
description: Patient Module
baseUri: http://acc.com/patient-api/{version}
mediaType: application/json
/getPatientDashboardDetail:
  description: Get the patient details for the dashboard
  post:
    body: 
      application/json:
        description: Provide the patient id as well date filter
        example: | 
          {
           "patient_id": "1",
           "date_filter": ""
          }
          
    responses:
      200:
        body: 
          application/json:
            example: |
               {
                  "status": true,
                   "statistic_report": {
                      "patient_fbs_scale": "",
                      "patient_ppbs_scale": "",
                      "patient_rbs_scale": "",
                      "patient_bp_scale": "",
                      "patient_bg_scale": "",
                      "output_param1": "",
                      "output_param2": "",
                      "output_param3": "",
                      "output_param4": ""
                     },
                   "summary_report": [{
                      "patient_id": "1",
                      "patient_name": "",
                      "patient_dob": "",
                      "output_param1": "",
                      "output_param2": "",
                      "output_param3": "",
                      "output_param4": ""
                   }],
                  "message": "login successfull",
                  "statusCode": "200"
                }
      401:
        body: 
          application/json:
            example: |
             {
                "status": "false",
                "errorMessage": "Patient ID doesn't exist",
                "errorCode": "1001",
                "statusCode": "401"
              }
/addDeviceDeatils:
  description: Add the device for the patient
  post:
    body: 
      application/json:
        description: Provide the device detail in the respect of patient
        example: |
          {
           "patientId": 3434,
           "deviceName": "Diamond Cuff",
           "deviceSerial": "12:2D:22:55:88",
           "deviceType": "BLOOD_GLUCOSE",
          }
          
    responses:
      200:
        body: 
          application/json:
            example: |
               {
                  "status": true,
                  "message": "device verified",
                  "statusCode": 200,
                  "data': {
                    "id":122,
                    "deviceName": "Diamond BG",
                    "deviceType": 'BLOOD_GLUCOSE',
                    "deviceSerial" : "12:2D:22:55:88"
                    }
                }
      403:
        body: 
          application/json:
            example: |
               {
                 "status": false,
                 "errorMessage": "Unable to verify the device",
                 "errorCode": "105",
                 "statusCode": 403
                }
/getAllDeviceDeatils/patient/{id}:
  description: Get the all device details for the patient
  get:
    responses:
      200:
        body: 
          application/json:
            example: |
               {
                 "status": true, 
                 "message": "device list",
                 "statusCode": 200,
                 "data" : [
                      {
                        "id":122,
                        "deviceName": "Diamond BG",
                        "deviceType": 'BLOOD_GLUCOSE'
                        "deviceSerial" : "12:2D:22:55:88"
                      },
                      {
                        "id":122
                        "deviceName": "Diamond BP",
                        "deviceType": 'BLOOD_PRESSURE'
                        "deviceSerial" : "12:2D:22:55:78"
                      }
                    ]                    
                }
      403:
        body: 
          application/json:
            example: |
               {
                  "status": false,
                   "errorMessage": "Unable to find the devices",
                   "errorCode": "105",
                   "statusCode": 403
                }
  